### PR TITLE
Fix the reload crash reported by https://github.com/logstash-plugins/…

### PR DESCRIPTION
**Pull request by craig-miskell-fluxfederation**
…logstash-input-syslog/issues/40

### CODE REVIEW

**Comment by nerophon** [comment]
@ph can you help out here? Do you know why the CI rejected this? Another user has hit the issue this claims to fix, so it'd be cool to get it in if it works :)

**Comment by jsvd** [comment]
The issue #40 mentions of the plugin raising an `IOError`, but this PR catches `Errno::EBADF` these two have different class hierarchies and I don't see a clear path where we can one and throw the other, so I'm not convinced this fixes the issue.

```
 :001 > Errno::EBADF.ancestors
 => [Errno::EBADF, SystemCallError, StandardError, Exception, Object, Kernel, BasicObject] 
 :002 > IOError.ancestors
 => [IOError, StandardError, Exception, Object, Kernel, BasicObject] 
```

**Comment by nerophon** [comment]
Alright, let's circle back to the issue.

**Comment by kares** [comment]
this is now a defunct PR (due #43) ... thanks for all the efforts :evergreen_tree:

**Pull request closed without merging**
