### PR TITLE
tmp pattern_path fix

### PR DESCRIPTION
**Pull request by colinsurprenant**
temporary fix to have the spec pass for an urgen mass-publish requirement.
relates to logstash-plugins/logstash-filter-grok#72

### CODE REVIEW

**Comment by jsvd** [comment]
jenkins, test it

**Comment by jsvd** [comment]
do the tests pass for you? I'm getting:

```
~/new_plugins/logstash-input-syslog (git)-[pr/25] % bundle update
bundle exec rspec
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.....
Using rake 11.1.1
Using cabin 0.8.1
Using clamp 0.6.5
Using coderay 1.1.1
Using concurrent-ruby 0.9.2
Using diff-lcs 1.2.5
Using ffi 1.9.10
Using filesize 0.0.4
Using gem_publisher 1.5.0
Using gems 0.8.3
Using i18n 0.6.9
Using insist 1.0.0
Using jar-dependencies 0.3.2
Using jrjackson 0.3.8
Using jruby-openssl 0.9.13
Using kramdown 1.10.0
Using ruby-maven-libs 3.3.3
Using minitar 0.5.4
Using method_source 0.8.2
Using slop 3.6.0
Using rubyzip 1.1.7
Using stud 0.0.22
Using thread_safe 0.3.5
Using polyglot 0.3.5
Using rspec-support 3.1.2
Using bundler 1.11.2
Using jls-grok 0.11.2
Using spoon 0.0.4
Using ruby-maven 3.3.10
Using treetop 1.4.15
Using rspec-core 3.1.7
Using rspec-expectations 3.1.2
Using rspec-mocks 3.1.3
Using pry 0.10.3
Using logstash-core-event-java 2.3.0.snapshot3
Using rspec 3.1.0
Using logstash-core 2.3.0.snapshot3
Using rspec-wait 0.0.8
Using logstash-core-plugin-api 1.0.0
Using logstash-devutils 0.0.18
Using logstash-codec-json 2.1.3
Using logstash-codec-plain 2.0.4
Using logstash-patterns-core 2.0.4
Using logstash-input-generator 2.0.4
Using logstash-output-null 2.0.4
Using logstash-filter-grok 2.0.5
Using logstash-filter-date 2.1.4
Using logstash-input-syslog 2.0.4 from source at `.`
Bundle updated!
bundle update  26.16s user 0.84s system 160% cpu 16.847 total
joaoduarte@Joaos-MBP ~/new_plugins/logstash-input-syslog (git)-[pr/25] % bundle exec rspec
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
FFF.FF.

Failures:

  1) LogStash::Inputs::Syslog should add unique tag when grok parsing fails
     Failure/Error: insist { syslog_event["priority"] } ==  164
     Insist::Failure:
       Expected 164, but got 0
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/comparators.rb:14:in `=='
     # ./spec/inputs/syslog_spec.rb:169:in `(root)'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'

  2) LogStash::Inputs::Syslog should properly handle locale and timezone
     Failure/Error: insist { event["@timestamp"].to_iso8601 } == "#{Time.now.year}-10-26T15:19:25.000Z"
     Insist::Failure:
       Expected "2016-10-26T15:19:25.000Z", but got "2016-03-24T15:17:10.847Z"
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/comparators.rb:14:in `=='
     # ./spec/inputs/syslog_spec.rb:117:in `(root)'
     # ./spec/inputs/syslog_spec.rb:116:in `(root)'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'

  3) LogStash::Inputs::Syslog should support non UTC timezone
     Failure/Error: insist { syslog_event["@timestamp"].to_iso8601 } == "#{Time.now.year}-10-26T20:19:25.000Z"
     Insist::Failure:
       Expected "2016-10-26T20:19:25.000Z", but got "2016-03-24T15:17:11.736Z"
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/comparators.rb:14:in `=='
     # ./spec/inputs/syslog_spec.rb:153:in `(root)'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'

  4) LogStash::Inputs::Syslog should properly handle priority, severity and facilities
     Failure/Error: insist { event["priority"] } == 164
     Insist::Failure:
       Expected 164, but got 0
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/comparators.rb:14:in `=='
     # ./spec/inputs/syslog_spec.rb:56:in `(root)'
     # ./spec/inputs/syslog_spec.rb:55:in `(root)'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'

  5) LogStash::Inputs::Syslog should properly handle no locale and no timezone
     Failure/Error: insist { event["@timestamp"].to_iso8601 } =~ /#{Time.now.year}-10-26T\d\d:19:25.000Z/
     Insist::Failure:
       Expected "2016-03-24T15:17:13.683Z" =~ /2016-10-26T\d\d:19:25.000Z/
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/insist-1.0.0/lib/insist/comparators19.rb:14:in `=~'
     # ./spec/inputs/syslog_spec.rb:142:in `(root)'
     # /Users/joaoduarte/.rvm/gems/jruby-1.7.23/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'

Finished in 4.9 seconds (files took 2.14 seconds to load)
7 examples, 5 failures

Failed examples:

rspec ./spec/inputs/syslog_spec.rb:158 # LogStash::Inputs::Syslog should add unique tag when grok parsing fails
rspec ./spec/inputs/syslog_spec.rb:90 # LogStash::Inputs::Syslog should properly handle locale and timezone
rspec ./spec/inputs/syslog_spec.rb:145 # LogStash::Inputs::Syslog should support non UTC timezone
rspec ./spec/inputs/syslog_spec.rb:32 # LogStash::Inputs::Syslog should properly handle priority, severity and facilities
rspec ./spec/inputs/syslog_spec.rb:121 # LogStash::Inputs::Syslog should properly handle no locale and no timezone

Randomized with seed 8218
```

**Comment by colinsurprenant** [comment]
yes, obviously, works for me:

1. setup env
```
rm -rf vendor/ Gemfile.lock
colin@colin-mbp13r (master) ~/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog:
colin@colin-mbp13r (master) ~/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog:
colin@colin-mbp13r (master) ~/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog: bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...........
Installing rake 11.1.1
Installing cabin 0.8.1
Installing clamp 0.6.5
Installing coderay 1.1.1
Installing concurrent-ruby 0.9.2
Installing diff-lcs 1.2.5
Installing ffi 1.9.10
Installing filesize 0.0.4
Installing gem_publisher 1.5.0
Installing gems 0.8.3
Installing i18n 0.6.9
Installing insist 1.0.0
Installing jar-dependencies 0.3.2
Installing jls-grok 0.11.2
Installing jrjackson 0.3.8
Installing jruby-openssl 0.9.13
Installing kramdown 1.10.0
Using ruby-maven-libs 3.3.3
Installing ruby-maven 3.3.10
Installing logstash-core-event-java 2.3.0.snapshot3
  jar dependencies for logstash-core-event-java-2.3.0.snapshot3-java.gemspec . . .
      com.fasterxml.jackson.core:jackson-core:2.7.1
      com.fasterxml.jackson.core:jackson-databind:2.7.1-1
Installing minitar 0.5.4
Installing method_source 0.8.2
Installing slop 3.6.0
Installing spoon 0.0.4
Installing pry 0.10.3
Installing rubyzip 1.1.7
Installing stud 0.0.22
Installing thread_safe 0.3.5
Installing polyglot 0.3.5
Installing treetop 1.4.15
Installing logstash-core 2.3.0.snapshot3
Installing logstash-core-plugin-api 1.0.0
Installing logstash-codec-json 2.1.3
Installing logstash-codec-plain 2.0.4
Installing rspec-support 3.1.2
Installing rspec-core 3.1.7
Installing rspec-expectations 3.1.2
Installing rspec-mocks 3.1.3
Installing rspec 3.1.0
Installing rspec-wait 0.0.8
Installing logstash-devutils 0.0.18
Installing logstash-input-generator 2.0.4
Installing logstash-output-null 2.0.4
Installing logstash-filter-date 2.1.4
Installing logstash-patterns-core 2.0.4
Installing logstash-filter-grok 2.0.5
Using logstash-input-syslog 2.0.4 from source at .
Using bundler 1.10.6
Updating files in vendor/cache
Bundle complete! 2 Gemfile dependencies, 48 gems now installed.
Bundled gems are installed into ./vendor.
Post-install message from jar-dependencies:

if you want to use the executable lock_jars then install ruby-maven gem before using lock_jars

   $ gem install ruby-maven -v '~> 3.3.3'

or add it as a development dependency to your Gemfile

   gem 'ruby-maven', '~> 3.3.3'
```

2. failing test before fix

```
bundle exec rspec
Using Accessor#strict_set for specs
NoMethodError: undefined method `pattern_path' for LogStash::Environment:Module
             Grok at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/gems/logstash-filter-grok-2.0.5/lib/logstash/filters/grok.rb:226
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/gems/logstash-filter-grok-2.0.5/lib/logstash/filters/grok.rb:139
          require at org/jruby/RubyKernel.java:1040
          require at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/lib/logstash/inputs/syslog.rb:1
          require at org/jruby/RubyKernel.java:1040
          require at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/lib/logstash/inputs/syslog.rb:5
             load at org/jruby/RubyKernel.java:1059
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/spec/inputs/syslog_spec.rb:1
             each at org/jruby/RubyArray.java:1613
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/spec/inputs/syslog_spec.rb:11
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1
  load_spec_files at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105
  load_spec_files at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105
            setup at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96
              run at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84
             load at org/jruby/RubyKernel.java:1059
           (root) at /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-syslog/vendor/bin/rspec:23
```

3. post fix tests
```
bundle exec rspec
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.Failed (Connection refused - Connection refused). Sleeping for 0.02
......

Finished in 4.53 seconds (files took 2.19 seconds to load)
7 examples, 0 failures

Randomized with seed 42388
```

**Comment by suyograo** [comment]
Tests pass for me. So LGTM

```
uyog@machine:~/ws/elastic/ls_plugins/logstash-input-syslog (pr/25)$ bundle exec rspec
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring jruby-launcher-1.1.1-java because its extensions are not built.  Try: gem pristine jruby-launcher --version 1.1.1
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.......

Finished in 4.53 seconds (files took 1.88 seconds to load)
7 examples, 0 failures

Randomized with seed 10670
```

**Comment by colinsurprenant** [comment]
bumping, merging, pushing.

**Comment by colinsurprenant** [comment]
oh, ^^ that could be a good Daft Punk style version :P

**Comment by colinsurprenant** [comment]
2.0.5 pushed to rubygems.

**Pull request merged**
